version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank
    ports:
      - "5432:5432"
    networks:
      - spring-postgres
    volumes:
      - postgres_dev:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - spring-postgres

volumes:
  postgres_dev:

networks:
  spring-postgres: